import Head from 'next/head'
import { useState } from 'react'
import { useWallet } from '@solana/wallet-adapter-react'
import { useEffect } from 'react'
import { fetchNfts } from '../../api/api_custom'
import HeaderRefund from 'common/HeaderRefund'
import FooterRefund from 'common/FooterRefund'
import BasicCard from 'components/BasicCard'
import GridFilters from 'components/GridFilters'
import BasicBreadcrumb from 'common/BasicBreadCrumb'

export function Placeholder() {
  return (
    <div className="h-[25rem] w-80 animate-pulse rounded-xl  bg-white bg-opacity-5 p-10"></div>
  )
}

export default function refund() {
  const { publicKey, connecting, connected, wallet } = useWallet()
  const [cards, setCards] = useState([])
  const [loading, setLoading] = useState(false)
  const [filters, setFilters] = useState({})
  useEffect(() => {
    if (!publicKey) return
    setCards([])
    setLoading(true)
    fetchNfts(publicKey, filters).then((res) => {
      setCards(res)
      setLoading(false)
    })
  }, [publicKey, filters])
  return (
    <div>
      <Head>
        <title>Honeyland staking pool</title>
        <meta name="description" content="Generated by Honeyland" />
        <link rel="icon" href="/favicon.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Urbanist:wght@300;400;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="flex h-screen flex-col">
        <HeaderRefund />
        <div className="container mx-auto flex-auto py-10">
          <BasicBreadcrumb title="Explore" />
          {publicKey && (
            <GridFilters
              filters={filters}
              updateFilter={(val) => setFilters(val)}
            />
          )}
          {!wallet && !connecting && !connected && (
            <h3 className="py-10 text-center text-2xl text-white">
              Please connect to your wallet
            </h3>
          )}
          <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {cards.map((card, index) => (
              <BasicCard data={card.data} key={index} />
            ))}
            {loading && <Placeholder />}
            {loading && <Placeholder />}
            {loading && <Placeholder />}
            {loading && <Placeholder />}
            {loading && <Placeholder />}
            {loading && <Placeholder />}
            {loading && <Placeholder />}
            {loading && <Placeholder />}
            {loading && <Placeholder />}
            {loading && <Placeholder />}
            {loading && <Placeholder />}
          </div>
        </div>
        <FooterRefund />
      </div>
    </div>
  )
}
