import Image from 'next/image'
import Leaderboard from './../components/Leaderboard/Leaderboard'
import { useLeaderboard } from './../providers/LeaderboardProvider'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import { Wallet } from '@saberhq/solana-contrib'
import { useWallet } from '@solana/wallet-adapter-react'
import { useEnvironmentCtx } from '../../providers/EnvironmentProvider'
import { styled } from '@mui/system'
import { WalletMultiButton } from '@solana/wallet-adapter-react-ui'
export const StyledWalletButton = styled(WalletMultiButton)`
  color: rgb(55, 65, 81, 1);
  &:hover {
    background: none !important;
  }
  .wallet-adapter-button {
    padding: 0px;
  }
`
const Header = () => {
  const { leaderboard } = useLeaderboard()
  const router = useRouter()
  const page = router.route.includes('refund') ? 'refund' : 'main'
  const wallet = useWallet()
  const ctx = useEnvironmentCtx()

  const [statistics, setStatistics] = useState({
    totalStakedNft: 0,
    totalScore: 0,
  })
  useEffect(() => {
    if (Array.isArray(leaderboard)) {
      const temp = {
        totalStakedNft: 0,
        totalScore: 0,
      }

      leaderboard.forEach((item) => {
        temp.totalStakedNft += item.nftCount
        temp.totalScore += item.score
      })
      setStatistics(temp)
    }
  }, [leaderboard])
  return (
    <div className="container mx-auto w-full">
      <div className="v-header">
        <Head>
          <title>Honeyland</title>
          <meta name="description" content="Generated by Honeyland" />
          <link rel="icon" type="image/x-icon" href="honeyland/favicon.ico" />
          <link
            rel="apple-touch-icon"
            sizes="76x76"
            href="honeyland//apple-touch-icon.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="honeyland/favicon-32x32.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="16x16"
            href="honeyland/favicon-16x16.png"
          />
          <link rel="manifest" href="honeyland/site.webmanifest" />
          <link
            rel="mask-icon"
            href="honeyland/safari-pinned-tab.svg"
            color="#5bbad5"
          />
          <meta name="msapplication-TileColor" content="#da532c" />
          <meta name="theme-color" content="#ffffff" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" />
          <link
            href="https://fonts.googleapis.com/css2?family=Lilita+One&display=swap"
            rel="stylesheet"
          />

          <link
            href="https://fonts.googleapis.com/css2?family=Roboto&display=swap"
            rel="stylesheet"
          />
        </Head>
        <div className="v-header-logo">
          <img src="honeyland/logo.png" width="100%" />
        </div>
        <div className="v-header-content">
          <div className="v-header-menu">
            <div className="v-header-menu-title">
              {page === 'refund'
                ? 'REFUNDING GENESIS EGGs'
                : 'GENESIS EGG INCUBATOR'}
            </div>
            <div className="v-header-menu-buttons">
              {page !== 'refund' && <Leaderboard />}

              {wallet.connecting ? (
                <button>CONNECTING...</button>
              ) : wallet.connected && wallet.publicKey ? (
                <button onClick={() => wallet.disconnect()}>
                  DISCONNECT WALLET
                </button>
              ) : (
                <WalletMultiButton />
              )}
            </div>
          </div>
          {page !== 'refund' && (
            <div className="v-header-statistics">
              <div className="v-header-statistics-box">
                <div className="v-header-statistics-box__count">
                  {statistics.totalStakedNft}
                </div>
                <div className="v-header-statistics-box__title">
                  Total Genesis Eggs Incubating
                </div>
              </div>
              <div className="v-header-statistics-box">
                <div className="v-header-statistics-box__count">
                  {(statistics.totalStakedNft * 0.0181).toFixed(2)}%
                </div>
                <div className="v-header-statistics-box__title">
                  % of Genesis Eggs Incubating
                </div>
              </div>
              <div className="v-header-statistics-box">
                <div className="v-header-statistics-box__count">
                  {statistics.totalScore}
                </div>
                <div className="v-header-statistics-box__title">
                  Total Incubating Points Earned
                </div>
              </div>
            </div>
          )}
        </div>
        <img src="honeyland/bee-01.png" className="v-header-top-bee" />
        <img src="honeyland/bee-02.png" className="v-header-bottom-bee" />
      </div>
    </div>
  )
}
export { Header }
