import Head from 'next/head'
export default function HeadDefault() {
  return (
    <Head>
      <title>Ultimate Meta Club</title>
      <meta name="description" content="Generated by Ultimate Meta Club" />
      <link
        rel="apple-touch-icon"
        sizes="76x76"
        href="/UMCStaking/apple-touch-icon.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="/UMCStaking/favicon-32x32.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="16x16"
        href="/UMCStaking/favicon-16x16.png"
      />
      <link rel="manifest" href="site.webmanifest" />
      <link rel="mask-icon" href="safari-pinned-tab.svg" color="#5bbad5" />
      <meta name="msapplication-TileColor" content="#da532c" />
      <meta name="theme-color" content="#ffffff" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link
        href="https://fonts.googleapis.com/css2?family=Lilita+One&display=swap"
        rel="stylesheet"
      />
    </Head>
  )
}
