on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: honeyland.azurecr.io
        username: ${{ secrets.acr_honeyland_username }}
        password: ${{ secrets.acr_honeyland_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t honeyland.azurecr.io/honey:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push honeyland.azurecr.io/honey:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_honey_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep frontend | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace frontend`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: frontend
        container-registry-url: honeyland.azurecr.io
        container-registry-username: ${{ secrets.acr_honeyland_username }}
        container-registry-password: ${{ secrets.acr_honeyland_password }}
        secret-name: honeydockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: frontend
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          honeyland.azurecr.io/honey:${{ github.sha }}
        imagepullsecrets: |
          honeydockerauth
